// src/app/pelis/sesion/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl } from '@angular/forms';
import {Router} from '@angular/router';
import { initializeApp } from 'firebase/app';
import { getAuth, signInWithEmailAndPassword, onAuthStateChanged } from "firebase/auth";
import { HistorialComponent } from '../../shared/historial/historial.component';
// import { ToastrService } from 'ngx-toastr';


const firebaseConfig = {
  apiKey: "AIzaSyBpHgWq8ejMsDi1mgMTg3KgxdTWoacs1FA",
  authDomain: "pelisapp-24714.firebaseapp.com",
  projectId: "pelisapp-24714",
  storageBucket: "pelisapp-24714.appspot.com",
  messagingSenderId: "505441685394",
  appId: "1:505441685394:web:f8d9417216ac07ace93b4b"
};

const app = initializeApp(firebaseConfig);

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
})

export class LoginComponent implements OnInit {

  loginForm = new FormGroup({
    email: new FormControl(""),
    password: new FormControl(""),
  });

  public error: boolean = false;
  public login: boolean = false;
  public mensaje: string = "";

  constructor( private router:Router, public his:HistorialComponent){}

  ngOnInit(): void {
  }

  
  onLogin(){

    this.error = false;

    const email =  this.loginForm.controls["email"].value;
    const pass =  this.loginForm.controls["password"].value;

    const regex = /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;

    if( !email.match(regex) ){

      this.error = true;
      this.mensaje = "El usuario debe ser un correo electrónico."

    } 

    if( email.length == 0 || pass.length == 0 ){

      this.error = true;
      this.mensaje = "Intruduce usuario y contraseña."

    } 

    if (this.error == false) {

      const auth = getAuth();

      signInWithEmailAndPassword(auth, email, pass)
      .then((userCredential) => {
          const user = userCredential;

          onAuthStateChanged(auth, (user) => {
            if (user) {
              const uid = user.uid;
            }
              
          })

          this.router.navigate([""]);
          // this.showSuccess()
          
      })
      .catch((error) => {
        this.error = true;
        
        if(error.code == "auth/wrong-password") {
          this.mensaje = "La contraseña para este usuario es incorrecta.";
        } 

        if(error.code == "auth/user-not-found") {
          this.mensaje = "El usuario no existe.";
        } 

      });

    }
      
  }

//   showSuccess() {
//     this.toastr.success('Usuario ' + this.loginForm.controls["email"].value + ' logueado correctamente.', 'Aviso')
// };

  }



<div align="center">

    <div style="max-width:500px" class="p-3 animate__animated animate__fadeIn">
    
        <h4 style="margin-top:10px;margin-bottom:20px">Accede a tu cuenta</h4>

        <div class="form-check card p-5">

        <form [formGroup] ="loginForm" (ngSubmit) = "onLogin()">
            
            <input 
                autocomplete="off"
                style ="text-align:center;border:1px solid green; outline: none; box-shadow: none; margin-bottom: 40px;"
                type="text" 
                class="ph form-control"
                placeholder="Usuario"
                formControlName ="email"
                >

            <input 
                autocomplete="off"
                style ="text-align:center;border:1px solid green; outline: none; box-shadow: none;  margin-bottom: 40px"
                type="password" 
                class="ph form-control"
                placeholder="Contraseña"
                formControlName ="password"
                >

            <button type="submit" style ="outline: none; box-shadow: none;" class="btn btn-success">Entrar</button>

            <!-- <p style="margin-top:20px; margin-bottom: -10px;"><a id="link1" href="#">He olvidado mi contraseña</a></p> -->
            <p style="margin-top:20px; margin-bottom: -10px;">¿No tienes cuenta? <a [routerLink]="[ '../sigin' ]" id="link1" href="#">Créala</a></p>

        </form>

        <div *ngIf="error == true" align="center">
            <div style="margin-top:45px;margin-bottom:-5px;width:100%" class="alert alert-danger">
                 {{mensaje}}
             </div>
         </div>

        </div>

    </div>

</div>

// React/TotalGifApp/src/components/Login.js
import React, { useState  } from 'react'
import { getAuth, signInWithEmailAndPassword, onAuthStateChanged } from 'firebase/auth';
import { useNavigate } from 'react-router-dom';
import { NavLink } from 'react-router-dom'


export const Login = () => {

  const [inputValue1, setInputValue1] = useState('');
  const [inputValue2, setInputValue2] = useState('');

  const [error, setError] = useState(false);
  const [mError, setMError] = useState('');

  const navigate = useNavigate();

  const handleInputChange1 = ( e ) => {
    setInputValue1( e.target.value );
  }

  const handleInputChange2 = ( e ) => {
    setInputValue2( e.target.value );
  }

  const handleSubmit = ( e ) => {
    e.preventDefault();

    const email = document.getElementById('email').value;
    const pass = document.getElementById('pass').value;

    const auth = getAuth();

    signInWithEmailAndPassword(auth, email, pass)
      .then((userCredential) => {
          const user = userCredential;

          onAuthStateChanged(auth, (user) => {
            if (user) {
              const uid = user.uid;

              navigate('../cuenta')
              
            }
              
          })
          
      }).catch((err) => {
        setError (true);
        
        if(err.code == "auth/invalid-email") {
          setMError("El correo electrónico no es válido");
        } 

        if(err.code == "auth/wrong-password") {
          setMError("La contraseña es incorrecta");
        } 

        if(err.code == "auth/user-not-found") {
          setMError("El usuario no existe");
        } 

        if(err.code == "auth/internal-error") {
          setMError("Debes completar usuario y contraseña");
        } 


      });

    

}

  return (
    <>
        <div className="margin"></div>

        <div align="center"><h2 className="cabecera animate__animated animate__fadeInUp">ACCEDE A TU CUENTA</h2></div>

        <div align="center">
          <div style={{maxWidth:500}}>
            <form onSubmit={ handleSubmit }>
                <input 
                    type="text"
                    value={ inputValue1 }
                    onChange={ handleInputChange1 }
                    placeholder="Usuario"
                    autoComplete='off'
                    id="email"
                    className='animate__animated animate__fadeInUp'
                />
                <input 
                    style={{marginTop:-10}}
                    type="password"
                    value={ inputValue2 }
                    onChange={ handleInputChange2 }
                    placeholder="Contraseña"
                    autoComplete='off'
                    id="pass"
                    className='animate__animated animate__fadeInUp'
                />

                {error ==true && <div style={{maxWidth:500}} className="error animate__animated animate__fadeIn"><b>{mError}</b></div>}

                <button className='hash animate__animated animate__fadeInUp'>
                  Entrar
                  </button>
            </form>
            <div className="animate__animated animate__fadeInUp"><span>¿No tienes cuenta?</span> <b><i><span><NavLink to="../signin">Crear</NavLink></span></i></b></div>
          </div>
        </div>
    </>
  )
}
